# Generated by Django 6.0.1 on 2026-02-03 05:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_foodentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseDayEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_dal', models.CharField(blank=True, max_length=100)),
                ('sold_chawal', models.CharField(blank=True, max_length=100)),
                ('sold_sabji', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FoodWaste',
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
