# Generated by Django 6.0.1 on 2026-02-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_closedayentry_delete_foodwaste_alter_foodentry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedayentry',
            name='chawal_waste',
            field=models.CharField(default=0),
        ),
        migrations.AddField(
            model_name='closedayentry',
            name='dal_waste',
            field=models.CharField(default=0),
        ),
        migrations.AddField(
            model_name='closedayentry',
            name='sabji_waste',
            field=models.CharField(default=0),
        ),
    ]
