# Generated by Django 6.0.1 on 2026-02-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_foodrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
