# Generated by Django 6.0.1 on 2026-02-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('food_prepared', models.FloatField()),
                ('food_sold', models.FloatField()),
                ('food_wasted', models.FloatField()),
                ('is_event_day', models.BooleanField(default=False)),
            ],
        ),
    ]
